export default defaultTheme = {
    $primaryColor: '#A7226E',
    $secondaryColor: '#EC2049',
    $accentColor: '#F7DB4F',
    $textOnPrimaryColor: '#fff',
    $textColor: '#222',
    $inverseTextColor: '#fff',
    $baseBackgroundColor: '#fafafa',

    $dividerColor: '#e1e8ee',
    $dividerVerticalMargin: 8,
    
    //card
    $cardTitleColor: '#43484d',
    $cardBackgroundColor: '#fff',
    $cardBorderColor: '$dividerColor',
    $cardPadding: 15,
    $cardMargin: 15,
    $cardFeaturedTitleFontSize: 18,
    $cardFeaturedSubtitleFontSize: 13,
    $cardBorderWidth: 1,
    $cardFeaturedTitleBottomMargin: 8,
    $cardFeaturedTitleColor: '#fff',
    $cardFeaturedTitleFontWeight: '800',
    $cardFeaturedSubtitleColor: '#fff',
    $cardFeaturedSubtitleFontWeight: '400',
    $cardDividerBottomMargin: 15,
    $cardTitleFontSize: 15,
    $cardTitleFontWeight: '600',
    $cardTitleBottomMargin: 15,
    $imageCardTitleTopMargin: 15,

    $h1FontSize: 40,
    $h2FontSize: 34,
    $h3FontSize: 28,
    $h4FontSize: 22,

    $fontSizeButton: 16,
    $fontSizeSmallButton: 14,
    $buttonContainerMargin: 16,
    $buttonPadding: 19,
    $smallButtonPadding: 12,
    $buttonIconColor: '#fff',

    $iconFontSize: 27,
    $iconColor: '$primaryColor',

    $containerPadding: 16,
    $titleFontSize: 20,
}